### PR TITLE
Add SmartTrades V2

### LINKED ISSUE #24: Smart Trades Version 2
Apparently the Smart Trades in the current version call the v1 3Commas API. Those calls will be blank for any new Smart Trades. 

Need to use this instead.

https://github.com/3commas-io/3commas-official-api-docs/blob/master/smart_trades_v2_api.md#get-smart-trade-history-permission-smart_trade_read-security-signed

Is there a way to submit a suggestion? Thanks!

### PR DESCRIPTION
**Pull request by hexate**
This is a partial implementation of SmartTrades V2. It is ABSOLUTELY a breaking change - but likely not a deal breaker as I'm pretty sure 3commas V1 apis don't actually work correctly anymore - so an upgrade is necessary anyway.

Caveats:
- It is incomplete, not all methods in v2 have been implemented (because I didn't need them) but should not be difficult to add.
- The swagger doc for 3commas api was not up to date at the time I wrote this, so I eyeballed the response objects as best I could. Some of them are not complete either (for example, I did not implement leverage DTOs).
- I renamed the original SmartTrade object to SmartTradeV1 and implemented the new version as SmartTrade in its own namespace. I did this to only have to change code minimally, but is not the cleanest way to do it. SmartTradeV1 can likely be deleted.

### CODE REVIEW

**Comment by MarcDrexler** [comment]
It's a breaking change indeed, but we should get rid of V1 anyway. 3commas themselves no longer want anyone to use it. In my opinion, we can remove V1 completely and the V2 namespace would then no longer be necessary. If you talk or read about smart trade from now on, it should only be v2 anyway.

@TheKimono what do you think?

**Comment by TheKimono** [comment]
> It's a breaking change indeed, but we should get rid of V1 anyway. 3commas themselves no longer want anyone to use it. In my opinion, we can remove V1 completely and the V2 namespace would then no longer be necessary. If you talk or read about smart trade from now on, it should only be v2 anyway.
> 
> @TheKimono what do you think?

I agree. There’s no need to keep backwards compatibility with the obsolete V1.

**Comment by prodigy** [comment]
Nice, I was just about to do the same. 😊 However, I noticed the `SmartTrade` object is missing the `ClosedAt` property:
```csharp
[JsonProperty("closed_at")]
public DateTime ClosedAt { get; set; }
```

**Comment by MarcDrexler** [comment]
@hexate 
I just removed the V1 stuff and replaced some string params with new enumerations.

@prodigy1
Property `ClosedAt` has been added.

**Comment by MarcDrexler** [comment]
@TheKimono I did some tests and can only say that it works so far. Let's merge and create a new package.

**Review by MarcDrexler — APPROVED** [review]

**Pull request merged**
